### ISSUE TITLE
Embedded pages with hash sign in the URL not working properly

### ISSUE THREAD

**Issue by sverkerEsriSE** [Esri/storymap-journal#86]
When adding two sections with the content type "Web page" and using URL:s with hash signs in them, the app will remove the hash sign and everything after that.

For example:

1. Create a new Storymap Journal
2. Add a section of type Web Page with this URL:
https://gi.karlstad.se/#layers=BGkarta/v/1/s/0,gatunamn_aggregated/v/1/s/0,karlstad/v/1/s/0,vy_mi_miljo_livsmedelskontroller_mobilanlaggning/v/1/s/0&center=150676,6584658&zoom=7&map=index_ssl
3. Add a section with the URL:
https://gi.karlstad.se/#layers=lm_visning_orto/v/1/s/0,gatunamn_aggregated/v/1/s/0,karlstad/v/1/s/0,vy_mi_miljo_livsmedelskontroller_mobilanlaggning/v/1/s/0

When viewing the app, it will only display the same map in both section, even though the URL was different (after the hash sign).

**Comment by asizer** [comment]
Hi there,

I've looked into this, and I think it's possible the issue lies with the webpage above. 

For example, if you add a Web Page section with this URL:
`https://underscorejs.org/#functions`
and then add one with this URL:
`https://underscorejs.org/#collections`
the webpage transitions from the `functions` anchor to the `collections` one when navigating between Map Journal sections.

Likewise, if you add a Web Page section that's a Web Scene Viewer with a hash for the slide number:
https://www.arcgis.com/home/webscene/viewer.html?webscene=13602f2c29ba42098e45786c7b996db3&ui=min#7
and then add a second section with this URL:
https://www.arcgis.com/home/webscene/viewer.html?webscene=13602f2c29ba42098e45786c7b996db3&ui=min#8
you'll see the webscene transitions between slide 7 and slide 8 when changing Map Journal sections.

In fact, you can see this outside a Map Journal. If you just open one of the webscene addresses above in a new tab, wait for it to load, then change the number after the hash and hit enter, you'll see the webscene shift to a different slide.

In contrast, if you open the first URL from `gi.karlstad.se` above, then replace everything after the hash with the hash on the second URL above and press enter, nothing happens.

Perhaps the app above could use a `onhashchange` listener?
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange

**Comment by asizer** [comment]
PS Here's a Map Journal that uses the Web Scene Viewer's slide hashes:
http://commteamre.maps.arcgis.com/apps/MapJournal/index.html?appid=fd1b0befa27d42ed91590e71d818a7c3
Sections 3, 4, 5, 6, and 8 share the same Web Scene Viewer with the same URL, but with different hashes for different slides. You can see the scene change layers and move locations, just by changing the slide hash.

**Comment by sverkerEsriSE** [comment]
@asizer Thank you for the quick reply. Your assertions look spot on, so I believe this issue can be closed.

I should have done some more thorough research before opening an issue.

Thanks again!
